# Generated by Django 2.1.7 on 2019-08-19 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geogebra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geogebra',
            name='height',
            field=models.IntegerField(default=600, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='geogebra',
            name='width',
            field=models.IntegerField(default=800, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
